name: Deploy Obsidian Vault with Quartz

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can specify the Node.js version you need

      - name: Install Quartz
        run: npm install -g @quartz/cli

      - name: Build static site
        run: quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

